gemini:
  model_name: gemini-2.5-flash #gemini-2.5-pro, gemini-2.5-flash-lite, gemini-2.0-flash, gemini-2.0-flash-lite
  temperature: 0.7
  max_tokens: 2048
  timeout: 30
  max_retries: 3

groq:
  model_name: llama-3.1-8b-instant
  temperature: 0.6
  max_tokens: 1024
  timeout: 25
  max_retries: 2

openai:
  model_name: gpt-4o
  temperature: 0.5
  max_tokens: 4096
  timeout: 20
  max_retries: 3
